<?php
define('STEAM_GROUP_API_PDO_HOSTNAME', '');
define('STEAM_GROUP_API_PDO_PORT', 3306);
define('STEAM_GROUP_API_PDO_USERNAME', '');
define('STEAM_GROUP_API_PDO_PASSWORD', '');
define('STEAM_GROUP_API_PDO_DATABASE', '');

define('STEAM_GROUP_API_STEAM_USERNAME', '');
define('STEAM_GROUP_API_STEAM_PASSWORD', '');
